import React, { useEffect } from "react";
import { useParams } from "wouter";
import { useQuery } from "@tanstack/react-query";

interface OrderLineRaw {
  id: number | string;
  itemId: string;
  itemName?: string;
  noun?: string;
  unitOfIssue?: string;
  qty?: number;
  quantity?: number;
  unitPriceUsd: number;
  extPriceUsd?: number;
  lineTotalUsd?: number;
}

interface OrderHeaderRaw {
  id: string;
  orderNo: string;
  nodeId: string;
  nodeName?: string;
  supplierId: string;
  supplierName?: string;
  status: string;
  priority: string;
  createdAt: string;
  requestedDeliveryAt: string;
  totalUsd: number;
  notes?: string | null;
}

interface OrderDetailRaw {
  order?: OrderHeaderRaw;
  lines?: OrderLineRaw[];
  // also support flat shape
  id?: string;
  orderNo?: string;
  nodeId?: string;
  supplierId?: string;
  status?: string;
  priority?: string;
  createdAt?: string;
  requestedDeliveryAt?: string;
  totalUsd?: number;
  notes?: string | null;
}

const BASE = (import.meta as any).env.BASE_URL?.replace(/\/$/, "") || "";

function fmtMoney(n: number) {
  return new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(n);
}

function fmtDate(iso: string) {
  try {
    return new Date(iso).toISOString().replace("T", " ").slice(0, 16) + "Z";
  } catch {
    return iso;
  }
}

export default function PurchaseOrder() {
  const { id } = useParams();

  const { data: raw, isLoading, error } = useQuery<OrderDetailRaw>({
    queryKey: ["order", id],
    queryFn: async () => {
      const r = await fetch(`${BASE}/api/orders/${id}`);
      if (!r.ok) throw new Error(`HTTP ${r.status}`);
      return r.json();
    },
    enabled: !!id,
  });

  const header: OrderHeaderRaw | undefined = raw?.order ?? (raw && raw.orderNo ? (raw as OrderHeaderRaw) : undefined);
  const lines = (raw?.lines ?? []).map((ln) => {
    const qty = ln.qty ?? ln.quantity ?? 0;
    const ext = ln.extPriceUsd ?? ln.lineTotalUsd ?? qty * (ln.unitPriceUsd ?? 0);
    return { ...ln, qty, extPriceUsd: ext };
  });

  useEffect(() => {
    document.documentElement.classList.remove("dark");
    document.title = header?.orderNo ? `PO ${header.orderNo}` : "Purchase Order";
    return () => {
      document.documentElement.classList.add("dark");
    };
  }, [header]);

  if (isLoading) {
    return (
      <div className="p-12 bg-white text-black min-h-screen font-serif">
        <p>Loading purchase order…</p>
      </div>
    );
  }

  if (error || !header) {
    return (
      <div className="p-12 bg-white text-black min-h-screen font-serif">
        <h1 className="text-2xl font-bold mb-4">Purchase Order Not Found</h1>
        <p className="font-mono text-sm">PO ID: {id}</p>
      </div>
    );
  }

  const data = header;
  const today = new Date().toISOString().slice(0, 10);

  return (
    <div className="bg-white text-black min-h-screen font-serif">
      <style>{`
        @media print {
          .no-print { display: none !important; }
          @page { size: letter; margin: 0.5in; }
          body { -webkit-print-color-adjust: exact; }
        }
        .gridbox { border: 1px solid #000; }
      `}</style>

      <div className="no-print bg-slate-100 border-b border-slate-300 p-3 flex gap-2 print:hidden">
        <button
          onClick={() => window.print()}
          className="bg-slate-900 text-white px-4 py-1.5 text-sm font-sans rounded"
        >
          Print
        </button>
        <button
          onClick={() => window.history.back()}
          className="bg-white border border-slate-400 text-slate-900 px-4 py-1.5 text-sm font-sans rounded"
        >
          Back
        </button>
        <span className="text-xs font-sans text-slate-600 ml-auto self-center">
          DMLSS-compatible MILSTRIP-style document
        </span>
      </div>

      <div className="max-w-[8.5in] mx-auto p-10">
        <header className="flex justify-between items-start border-b-2 border-black pb-4 mb-6">
          <div>
            <h1 className="text-3xl font-bold tracking-tight">PURCHASE ORDER</h1>
            <p className="text-xs uppercase tracking-widest mt-1">
              U.S. Indo-Pacific Command — Medical Logistics
            </p>
            <p className="text-[10px] mt-1 text-slate-700">
              For Official Use Only · DMLSS Compatible · Generated by IRONVEIN — INDOPACOM Resilient Operational Network for Vital Expeditionary Inventory Nodes
            </p>
          </div>
          <div className="text-right">
            <div className="text-2xl font-mono font-bold">{data.orderNo}</div>
            <div className="text-xs mt-1">PRINTED {today}</div>
            <div className="text-xs">PRIORITY: <span className="font-bold">{data.priority}</span></div>
            <div className="text-xs">STATUS: <span className="font-bold">{data.status}</span></div>
          </div>
        </header>

        <section className="grid grid-cols-2 gap-4 mb-6 text-sm">
          <div className="gridbox p-3">
            <div className="text-[10px] uppercase tracking-wider text-slate-600 mb-1">Ship To (Consignee)</div>
            <div className="font-bold">{data.nodeName || data.nodeId}</div>
            <div className="text-xs text-slate-700">Node ID: {data.nodeId}</div>
          </div>
          <div className="gridbox p-3">
            <div className="text-[10px] uppercase tracking-wider text-slate-600 mb-1">Vendor</div>
            <div className="font-bold">{data.supplierName || data.supplierId}</div>
            <div className="text-xs text-slate-700">Supplier ID: {data.supplierId}</div>
          </div>
          <div className="gridbox p-3">
            <div className="text-[10px] uppercase tracking-wider text-slate-600 mb-1">Order Date</div>
            <div className="font-mono">{fmtDate(data.createdAt)}</div>
          </div>
          <div className="gridbox p-3">
            <div className="text-[10px] uppercase tracking-wider text-slate-600 mb-1">Requested Delivery</div>
            <div className="font-mono">{fmtDate(data.requestedDeliveryAt)}</div>
          </div>
        </section>

        <table className="w-full text-sm border-collapse mb-6">
          <thead>
            <tr className="bg-slate-200 text-left text-[11px] uppercase tracking-wider">
              <th className="border border-black px-2 py-1.5 w-10">Ln</th>
              <th className="border border-black px-2 py-1.5">NIIN / Item</th>
              <th className="border border-black px-2 py-1.5">Description</th>
              <th className="border border-black px-2 py-1.5 w-16">U/I</th>
              <th className="border border-black px-2 py-1.5 w-16 text-right">Qty</th>
              <th className="border border-black px-2 py-1.5 w-24 text-right">Unit Price</th>
              <th className="border border-black px-2 py-1.5 w-28 text-right">Extended</th>
            </tr>
          </thead>
          <tbody>
            {lines.map((ln, idx) => (
              <tr key={ln.id} className="align-top">
                <td className="border border-black px-2 py-1.5 font-mono">{String(idx + 1).padStart(3, "0")}</td>
                <td className="border border-black px-2 py-1.5 font-mono text-xs">{ln.itemId}</td>
                <td className="border border-black px-2 py-1.5">{ln.itemName || ln.noun || "—"}</td>
                <td className="border border-black px-2 py-1.5 font-mono text-xs">{ln.unitOfIssue || "EA"}</td>
                <td className="border border-black px-2 py-1.5 text-right font-mono">{ln.qty}</td>
                <td className="border border-black px-2 py-1.5 text-right font-mono">{fmtMoney(ln.unitPriceUsd)}</td>
                <td className="border border-black px-2 py-1.5 text-right font-mono">{fmtMoney(ln.extPriceUsd)}</td>
              </tr>
            ))}
            {lines.length === 0 && (
              <tr>
                <td className="border border-black px-2 py-3 text-center text-slate-500 italic" colSpan={7}>
                  No line items returned by the order detail endpoint.
                </td>
              </tr>
            )}
          </tbody>
          <tfoot>
            <tr className="bg-slate-100">
              <td className="border border-black px-2 py-2 font-bold text-right" colSpan={6}>
                ORDER TOTAL
              </td>
              <td className="border border-black px-2 py-2 text-right font-mono font-bold">
                {fmtMoney(data.totalUsd)}
              </td>
            </tr>
          </tfoot>
        </table>

        {data.notes && (
          <section className="gridbox p-3 mb-6 text-sm">
            <div className="text-[10px] uppercase tracking-wider text-slate-600 mb-1">
              Justification / Notes
            </div>
            <div className="leading-snug">{data.notes}</div>
          </section>
        )}

        <section className="grid grid-cols-2 gap-8 mt-12 text-sm">
          <div>
            <div className="border-t border-black pt-1">
              <div className="text-[10px] uppercase tracking-wider">Requesting Officer</div>
              <div className="text-xs mt-1">Signature / Date</div>
            </div>
          </div>
          <div>
            <div className="border-t border-black pt-1">
              <div className="text-[10px] uppercase tracking-wider">Approving Authority</div>
              <div className="text-xs mt-1">Signature / Date</div>
            </div>
          </div>
        </section>

        <footer className="mt-10 pt-3 border-t border-slate-400 text-[10px] text-slate-600 flex justify-between">
          <span>USINDOPACOM IRONVEIN — Resilient Operational Network for Vital Expeditionary Inventory Nodes</span>
          <span>Document Class: Operational · Distribution: As Authorized</span>
        </footer>
      </div>
    </div>
  );
}
