import {
  pgTable,
  text,
  timestamp,
  serial,
  uniqueIndex,
  index,
} from "drizzle-orm/pg-core";

// Project-wide tags. A tag has a unique slug (used in URLs) and a
// human-friendly name. `source` records whether it was created manually
// or generated by AI; `color` is a tailwind hue token (e.g. "amber",
// "sky") chosen by the seed/admin so chips render consistently.
export const tags = pgTable(
  "tags",
  {
    id: text("id").primaryKey(),
    name: text("name").notNull(),
    slug: text("slug").notNull(),
    color: text("color").notNull().default("slate"),
    description: text("description").notNull().default(""),
    // 'manual' | 'ai'
    source: text("source").notNull().default("manual"),
    createdBy: text("created_by").notNull().default("system"),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => ({
    slugUnique: uniqueIndex("tags_slug_unique").on(t.slug),
  }),
);

// Polymorphic assignment of a tag to one of the supported entities.
// `entityType` ∈ { node, item, supplier, order, shipment, scenario, alert, blood_lot }.
// `appliedBy` ∈ { manual, ai }. For AI assignments we also keep the model
// id and a short rationale so the UI can show why the tag was suggested.
export const tagAssignments = pgTable(
  "tag_assignments",
  {
    id: serial("id").primaryKey(),
    tagId: text("tag_id").notNull(),
    entityType: text("entity_type").notNull(),
    entityId: text("entity_id").notNull(),
    appliedBy: text("applied_by").notNull().default("manual"),
    appliedByActor: text("applied_by_actor").notNull().default("system"),
    aiModel: text("ai_model"),
    aiProvider: text("ai_provider"),
    rationale: text("rationale"),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => ({
    uniq: uniqueIndex("tag_assignments_unique").on(
      t.tagId,
      t.entityType,
      t.entityId,
    ),
    byEntity: index("tag_assignments_by_entity").on(t.entityType, t.entityId),
    byTag: index("tag_assignments_by_tag").on(t.tagId),
  }),
);

export type Tag = typeof tags.$inferSelect;
export type TagAssignment = typeof tagAssignments.$inferSelect;
export type NewTag = typeof tags.$inferInsert;
export type NewTagAssignment = typeof tagAssignments.$inferInsert;

export const TAG_ENTITY_TYPES = [
  "node",
  "item",
  "supplier",
  "order",
  "shipment",
  "scenario",
  "alert",
  "blood_lot",
] as const;
export type TagEntityType = (typeof TAG_ENTITY_TYPES)[number];

export const TAG_COLORS = [
  "slate",
  "rose",
  "amber",
  "emerald",
  "sky",
  "violet",
  "fuchsia",
  "cyan",
  "lime",
  "orange",
] as const;
export type TagColor = (typeof TAG_COLORS)[number];
